Repository prgrms-be-devcourse/NBE1_2_Team8, pull requests merged in 2024-10, with the labels that each got.

#53 [feat]모집글 수동&자동 마감 기능 구현
  backend/src/main/java/org/prgrms/devconnect/DevconnectApplication.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/BoardController.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardQueryService.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionCode.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/entity/Board.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/repository/BoardRepository.java
Labels: ✨FEAT✨

#57 [feat] 댓글 엔티티 관련 로직 개발
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardScheduleService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/entity/Board.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/entity/Comment.java
Labels: ✨FEAT✨

#58 [feat] 알림 전체 조회 api 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/alarm/AlarmController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/alarm/dto/response/AlarmGetResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/alarm/dto/response/AlarmsGetResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/service/alarm/AlarmCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/alarm/AlarmQueryService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/event/EventHandler.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/repository/AlarmRepository.java
  backend/src/test/java/org/prgrms/devconnect/api/service/alarm/AlarmCommandServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/api/service/alarm/AlarmQueryServiceTest.java
Labels: ✨FEAT✨

#60 [feat] 메세지 보내기, 조회하기 기능
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/ChattingControllor.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/response/ChatPartResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/response/ChatRoomListResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/response/MessageFullResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/response/MessageResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/service/chatting/ChattingCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/chatting/ChattingQueryService.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionCode.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/entity/Message.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/repository/MessageRepository.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/repository/custom/ChatPartRepositoryCustom.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/repository/custom/ChatPartRepositoryCustomImpl.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/member/repository/custom/MemberRepositoryCustom.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/member/repository/custom/MemberRepositoryCustomImpl.java
  backend/src/test/java/org/prgrms/devconnect/domain/define/chatting/ChattingCommendServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/domain/define/chatting/ChattingQueryServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/domain/define/chatting/ChattingServiceTest.java
Labels: ✨FEAT✨

#63 [feat]댓글 생성 로직 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/comment/CommentController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/comment/dto/CommentCreateRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/service/comment/CommentCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/comment/CommentQueryService.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/comment/CommentException.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/entity/Comment.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/repository/CommentRepository.java
Labels: ✨FEAT✨

#66 댓글 조회 기능 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/comment/CommentController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/comment/dto/request/CommentCreateRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/comment/dto/response/CommentResponseDto.java
  backend/src/main/java/org/prgrms/devconnect/api/service/comment/CommentCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/comment/CommentQueryService.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionCode.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/entity/Comment.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/repository/CommentRepository.java
  backend/src/test/java/org/prgrms/devconnect/api/service/comment/CommentCommandServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/api/service/comment/CommentQueryServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/domain/define/fixture/CommentFixture.java
Labels: ✨FEAT✨

#68 [feat] 관심 게시글 생성, 삭제
  backend/src/main/java/org/prgrms/devconnect/api/controller/interest/InterestController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/interest/dto/request/InterestBoardRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/service/interest/InterestCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/interest/InterestQueryService.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionCode.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/interest/InterestException.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/interest/entity/InterestBoard.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/interest/entity/InterestJobPost.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/interest/repository/InterestBoardRepository.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/interest/repository/InterestJobPostRepository.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/member/repository/FavoriteBoardRepository.java
  backend/src/test/java/org/prgrms/devconnect/api/service/interest/InterestCommandServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/api/service/interest/InterestQueryServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/domain/define/fixture/InterestFixture.java
Labels: ✨FEAT✨

#67 [feat] 알림 단일 삭제 API 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/alarm/AlarmController.java
  backend/src/main/java/org/prgrms/devconnect/api/service/alarm/AlarmCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/alarm/AlarmQueryService.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/alarm/AlarmException.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/repository/AlarmRepository.java
  backend/src/main/resources/application.yaml
  backend/src/test/java/org/prgrms/devconnect/api/service/alarm/AlarmCommandServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/api/service/alarm/AlarmQueryServiceTest.java
Labels: ✨FEAT✨

#71 [feat] 웹소켓 통신 구현
  backend/build.gradle
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/ChatWebSocketController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/ChattingControllor.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/request/JoinRequest.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/request/MessageRequest.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/response/MessageResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/dto/request/MemberCreateRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/test/ChatTestController.java
  backend/src/main/java/org/prgrms/devconnect/api/service/chatting/ChattingCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/chatting/ChattingQueryService.java
  backend/src/main/java/org/prgrms/devconnect/common/config/WebSocketConfig.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionCode.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/entity/ChatParticipation.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/entity/Message.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/repository/ChatParticipationRepository.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/repository/custom/ChatPartRepositoryCustomImpl.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/member/entity/Member.java
  backend/src/main/resources/templates/SimpleChatTest.html
  backend/src/test/java/org/prgrms/devconnect/domain/define/chatting/ChattingQueryServiceTest.java
Labels: ✨FEAT✨

#73 [feat] 댓글 수정&삭제 로직 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/comment/CommentController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/comment/dto/request/CommentUpdateRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/comment/dto/response/CommentResponseDto.java
  backend/src/main/java/org/prgrms/devconnect/api/service/comment/CommentCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/comment/CommentQueryService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/entity/Comment.java
  backend/src/test/java/org/prgrms/devconnect/api/service/comment/CommentCommandServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/domain/define/fixture/CommentFixture.java
Labels: ✨FEAT✨

#79 [feat] 알림 읽음 처리 로직 구현
  backend/src/main/java/org/prgrms/devconnect/api/service/alarm/AlarmQueryService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/entity/Alarm.java
  backend/src/test/java/org/prgrms/devconnect/api/service/alarm/AlarmQueryServiceTest.java
Labels: ✨FEAT✨

#75 [feat] 관심 채용 공고 리스트 조회, 생성, 삭제
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/dto/response/BoardInfoResponseDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/interest/InterestController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/interest/dto/request/InterestJobPostRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/interest/dto/response/InterestResponseDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/jobpost/dto/response/JobPostInfoResponseDto.java
  backend/src/main/java/org/prgrms/devconnect/api/service/interest/InterestCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/interest/InterestQueryService.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionCode.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/interest/repository/InterestJobPostRepository.java
  backend/src/test/java/org/prgrms/devconnect/api/service/interest/InterestCommandServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/api/service/interest/InterestQueryServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/domain/define/fixture/InterestFixture.java
  backend/src/test/java/org/prgrms/devconnect/domain/define/fixture/JobPostFixture.java
  backend/src/test/resources/application-test.yaml
Labels: ✨FEAT✨

#76 [feat] 알림 전체 삭제 API 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/alarm/AlarmController.java
  backend/src/main/java/org/prgrms/devconnect/api/service/alarm/AlarmCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/alarm/AlarmQueryService.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionCode.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/repository/AlarmRepository.java
  backend/src/test/java/org/prgrms/devconnect/api/service/alarm/AlarmCommandServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/api/service/alarm/AlarmQueryServiceTest.java
Labels: ✨FEAT✨

#77 [feat] 채팅 도메인 swagger 적용
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/ChattingControllor.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/request/ChatRoomRequest.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/response/ChatPartResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/response/ChatRoomListResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/response/MessageFullResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/response/MessageResponse.java
Labels: ✨FEAT✨

#83 [feat]단일 및 전체 게시물 조회
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/BoardController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/dto/response/BoardResponseDto.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardQueryService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/repository/BoardRepository.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/member/repository/MemberRepository.java
Labels: ✨FEAT✨

#81 [feat] 기술 스택 조회 기능
  backend/src/main/java/org/prgrms/devconnect/api/controller/techstack/TechStackController.java
  backend/src/main/java/org/prgrms/devconnect/api/service/techstack/TechStackQueryService.java
  backend/src/test/java/org/prgrms/devconnect/api/service/techstack/TechStackQueryServiceTest.java
Labels: ✨FEAT✨

#89 [feat] 각 알림 발생 서비스 메소드에 AOP 적용
  backend/src/main/java/org/prgrms/devconnect/api/service/alarm/AlarmCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/comment/CommentCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/interest/InterestQueryService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/aop/AlarmCreater.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/event/EventHandler.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/event/RegisteredCommentOnBoardEvent.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/event/RegisteredReceivedMessageEvent.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/event/RegisteredReplyCommentEvent.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/event/RegisteredUrgentEvent.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/event/RegisteredWelcomeEvent.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/interest/entity/InterestBoard.java
  backend/src/test/java/org/prgrms/devconnect/api/service/alarm/AlarmCommandServiceTest.java
Labels: ✨FEAT✨

#87 [feat] 읽지 않은 알림 수 조회 API 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/alarm/AlarmController.java
  backend/src/main/java/org/prgrms/devconnect/api/service/alarm/AlarmQueryService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/repository/AlarmRepository.java
  backend/src/test/java/org/prgrms/devconnect/api/service/alarm/AlarmQueryServiceTest.java
Labels: ✨FEAT✨

#90 [feat] 공고 조회/삭제 api 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/jobpost/JobPostController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/jobpost/dto/response/JobPostInfoResponseDto.java
  backend/src/main/java/org/prgrms/devconnect/api/service/jobpost/JobPostCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/jobpost/JobPostQueryService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/jobpost/entity/JobPost.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/jobpost/repository/JobPostRepository.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/jobpost/repository/custom/JobPostRepositoryCustom.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/jobpost/repository/custom/JobPostRepositoryImpl.java
Labels: ✨FEAT✨

#92 [feat] 버그리포트 CRUD 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/bugreport/BugReportController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/bugreport/dto/request/BugReportRequest.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/bugreport/dto/request/BugReportUpdateRequest.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/bugreport/dto/response/BugReportResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/ChattingControllor.java
  backend/src/main/java/org/prgrms/devconnect/api/service/bugreport/BugReportCommendService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/bugreport/BugReportQueryService.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionCode.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/bugreport/BugReportException.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/bugreport/entity/BugReport.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/bugreport/repository/BugReportRepository.java
  backend/src/test/java/org/prgrms/devconnect/api/service/bugreport/BugReportCommendServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/api/service/bugreport/BugReportQueryServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/api/service/chatting/ChattingCommendServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/api/service/chatting/ChattingQueryServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/domain/define/fixture/BugReportFixture.java
Labels: ✨FEAT✨

#91 [feat]인기 모집글/필터링/사용자 관심분야 기준 조회
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/BoardController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/dto/BoardFilterDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/dto/request/BoardTechStackRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/dto/response/BoardResponseDto.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardQueryService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/member/MemberQueryService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/repository/BoardRepository.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/repository/custom/BoardRepositoryCustom.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/repository/custom/BoardRepositoryCustomImpl.java
  backend/src/test/java/org/prgrms/devconnect/api/service/board/BoardCommandServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/api/service/board/BoardQueryServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/api/service/board/BoardScheduleServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/api/service/board/BoardServiceTest.java
Labels: ✨FEAT✨

#97 [feat] 조회수,좋아요 증가 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/jobpost/JobPostController.java
  backend/src/main/java/org/prgrms/devconnect/api/service/jobpost/JobPostQueryService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/jobpost/entity/JobPost.java
Labels: ✨FEAT✨

#93 [feat] 스프링 시큐리티 적용
  backend/build.gradle
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/MemberController.java
  backend/src/main/java/org/prgrms/devconnect/api/service/member/MemberCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/member/MemberQueryService.java
  backend/src/main/java/org/prgrms/devconnect/common/auth/CustomerMemberDetailsService.java
  backend/src/main/java/org/prgrms/devconnect/common/auth/JwtService.java
  backend/src/main/java/org/prgrms/devconnect/common/auth/filter/JwtTokenAuthenticationFilter.java
  backend/src/main/java/org/prgrms/devconnect/common/auth/filter/LoginAuthenticationFilter.java
  backend/src/main/java/org/prgrms/devconnect/common/auth/handler/LoginFailureHandler.java
  backend/src/main/java/org/prgrms/devconnect/common/auth/handler/LoginSuccessHandler.java
  backend/src/main/java/org/prgrms/devconnect/common/auth/redis/RefreshToken.java
  backend/src/main/java/org/prgrms/devconnect/common/auth/redis/RefreshTokenRepository.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionCode.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/refresh/RefreshTokenException.java
  backend/src/main/java/org/prgrms/devconnect/domain/config/RedisConfig.java
  backend/src/main/java/org/prgrms/devconnect/domain/config/SecurityConfig.java
  backend/src/main/java/org/prgrms/devconnect/domain/config/SwaggerConfig.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/member/entity/Member.java
  backend/src/main/resources/application.yaml
  backend/src/test/java/org/prgrms/devconnect/api/service/member/MemberCommandServiceTest.java
  backend/src/test/resources/application-test.yaml
Labels: ✨FEAT✨

#100 [feat] 알림 메일 전송 기능 구현
  backend/build.gradle
  backend/src/main/java/org/prgrms/devconnect/api/service/alarm/EmailService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/alarm/config/MailConfig.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionCode.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/alarm/EmailException.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/event/EventHandler.java
  backend/src/main/resources/application.yaml
  backend/src/main/resources/templates/emailForm.html
Labels: ✨FEAT✨

#102 [feat] 공고별 각종 조회로직 추가
  backend/src/main/java/org/prgrms/devconnect/api/controller/jobpost/JobPostController.java
  backend/src/main/java/org/prgrms/devconnect/api/service/jobpost/JobPostQueryService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/jobpost/repository/custom/JobPostRepositoryCustom.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/jobpost/repository/custom/JobPostRepositoryImpl.java
Labels: ✨FEAT✨

#106 [feat:]채용공고 스웨거 적용
  backend/src/main/java/org/prgrms/devconnect/api/controller/jobpost/JobPostController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/jobpost/dto/response/JobPostInfoResponseDto.java
Labels: ✨FEAT✨

#107 [docs] 게시글 스웨거 적용
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/BoardController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/dto/request/BoardCreateRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/dto/request/BoardTechStackRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/dto/response/BoardInfoResponseDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/dto/response/BoardResponseDto.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardQueryService.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionCode.java
  backend/src/test/java/org/prgrms/devconnect/api/service/board/BoardQueryServiceTest.java
Labels: :page_facing_up: DOCS :page_facing_up:

#108 [docs] 알림 스웨거 적용
  backend/src/main/java/org/prgrms/devconnect/api/controller/alarm/AlarmController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/alarm/dto/response/AlarmGetResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/alarm/dto/response/AlarmsGetResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/swagger/SwaggerConfig.java
Labels: :page_facing_up: DOCS :page_facing_up:

#114 [docs] 관심 게시글 & 관심 채용 공고 관련 api에 swagger 적용
  backend/src/main/java/org/prgrms/devconnect/api/controller/interest/InterestController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/interest/dto/request/InterestBoardRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/interest/dto/request/InterestJobPostRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/interest/dto/response/InterestResponseDto.java
Labels: :page_facing_up: DOCS :page_facing_up:

#113 [feat] 스프링 시큐리티에 따른 도메인별 수정
  backend/src/main/java/org/prgrms/devconnect/api/controller/alarm/AlarmController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/BoardController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/dto/request/BoardCreateRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/bugreport/BugReportController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/bugreport/dto/request/BugReportRequest.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/bugreport/dto/response/BugReportResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/comment/CommentController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/comment/dto/request/CommentCreateRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/interest/InterestController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/interest/dto/request/InterestBoardRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/interest/dto/request/InterestJobPostRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/jobpost/JobPostController.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardQueryService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/comment/CommentCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/interest/InterestCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/jobpost/JobPostCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/jobpost/JobPostQueryService.java
  backend/src/main/java/org/prgrms/devconnect/api/swagger/SwaggerConfig.java
  backend/src/main/java/org/prgrms/devconnect/domain/config/SecurityConfig.java
  backend/src/main/java/org/prgrms/devconnect/domain/config/SwaggerConfig.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/aop/AlarmCreater.java
Labels: ✨FEAT✨

#118 [docs] 멤버, 기술스택 Swagger 적용
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/MemberController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/dto/request/MemberCreateRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/dto/request/MemberLoginRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/dto/response/MemberResponseDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/techstack/TechStackController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/techstack/dto/response/TechStackResponseDto.java
Labels: :page_facing_up: DOCS :page_facing_up:

#127 [feat] 사용자 관심스택별 공고조회
  backend/src/main/java/org/prgrms/devconnect/api/controller/jobpost/JobPostController.java
  backend/src/main/java/org/prgrms/devconnect/api/service/jobpost/JobPostQueryService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/jobpost/repository/custom/JobPostRepositoryCustom.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/jobpost/repository/custom/JobPostRepositoryImpl.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/member/entity/Member.java
Labels: ✨FEAT✨

#124 [refactor] 알림 로직에서 알림 생성 로직을 비동기로 실행하도록 변경
  backend/src/main/java/org/prgrms/devconnect/DevconnectApplication.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/event/EventHandler.java
Labels: :hammer:refactor:hammer:

#123 [feat] 관심 게시물 및 관심 채용공고 등록/해제 시 좋아요 증가/감소 기능 추가
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/BoardController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/jobpost/JobPostController.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardQueryService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/interest/InterestCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/jobpost/JobPostCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/jobpost/JobPostQueryService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/entity/Board.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/repository/BoardRepository.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/jobpost/entity/JobPost.java
Labels: ✨FEAT✨

#132 [feat] 모집글 상세, 채용 공고 상세 페이지 작성
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/BoardController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/jobpost/JobPostController.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardQueryService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/jobpost/JobPostCommandService.java
  backend/src/main/java/org/prgrms/devconnect/view/ViewController.java
  backend/src/main/resources/templates/board-detail.html
  backend/src/main/resources/templates/index.html
  backend/src/main/resources/templates/job-detail.html
Labels: ✨FEAT✨

#131 [fix] 종료 날짜가 지났을때는 false 반환
  backend/src/main/java/org/prgrms/devconnect/domain/define/interest/entity/InterestBoard.java
Labels: 🐞BUG🐞
