Repository prgrms-be-devcourse/NBE1_2_Team8, pull requests merged in 2024-09, with the labels that each got.

#4 [docs] readme 수정
  README.md
Labels: :page_facing_up: DOCS :page_facing_up:

#8 [docs] readme 수정
  README.md
Labels: :page_facing_up: DOCS :page_facing_up:

#9 Init/#1
  backend/settings.gradle
  backend/src/main/java/org/prgrms/devconnect/DevconnectApplication.java
  backend/src/main/java/org/prgrms/devconnect/alarm/entity/Alarm.java
  backend/src/main/java/org/prgrms/devconnect/board/entity/Board.java
  backend/src/main/java/org/prgrms/devconnect/board/entity/BoardTechStackMapping.java
  backend/src/main/java/org/prgrms/devconnect/board/entity/Comment.java
  backend/src/main/java/org/prgrms/devconnect/board/entity/constant/BoardStatus.java
  backend/src/main/java/org/prgrms/devconnect/bugreport/entity/BugReport.java
  backend/src/main/java/org/prgrms/devconnect/bugreport/entity/constant/BugType.java
  backend/src/main/java/org/prgrms/devconnect/chatting/entity/ChatParticipation.java
  backend/src/main/java/org/prgrms/devconnect/chatting/entity/ChattingRoom.java
  backend/src/main/java/org/prgrms/devconnect/chatting/entity/Message.java
  backend/src/main/java/org/prgrms/devconnect/chatting/entity/constant/ChattingRoomStatus.java
  backend/src/main/java/org/prgrms/devconnect/common/audit/CreateTimestamp.java
  backend/src/main/java/org/prgrms/devconnect/common/audit/Timestamp.java
  backend/src/main/java/org/prgrms/devconnect/jobpost/entity/JobPost.java
  backend/src/main/java/org/prgrms/devconnect/jobpost/entity/JobPostTechStackMapping.java
  backend/src/main/java/org/prgrms/devconnect/jobpost/entity/constant/JobType.java
  backend/src/main/java/org/prgrms/devconnect/jobpost/entity/constant/Status.java
  backend/src/main/java/org/prgrms/devconnect/member/entity/Member.java
  backend/src/main/java/org/prgrms/devconnect/member/entity/MemberTechStackMapping.java
  backend/src/main/java/org/prgrms/devconnect/member/entity/constant/Interest.java
  backend/src/main/java/org/prgrms/devconnect/member/entity/favoriteboard/FavoriteBoard.java
  backend/src/main/java/org/prgrms/devconnect/member/entity/favoritejobpost/FavoriteJobPost.java
  backend/src/main/java/org/prgrms/devconnect/techstack/entity/TechStack.java
  backend/src/main/java/org/prgrms/ola/OlaApplication.java
  backend/src/main/resources/application.yaml
  backend/src/test/java/org/prgrms/devconnect/DevconnectApplicationTests.java
Labels: 🛠️INIT🛠️

#24 [feat] 채팅관련 엔티티 여러 메서드 추가
  backend/src/main/java/org/prgrms/devconnect/chatting/entity/ChatParticipation.java
  backend/src/main/java/org/prgrms/devconnect/chatting/entity/ChattingRoom.java
  backend/src/main/java/org/prgrms/devconnect/chatting/entity/Message.java
Labels: ✨FEAT✨

#27 [init] Exception핸들러 구현
  backend/src/main/java/org/prgrms/devconnect/common/exception/BusinessLogicException.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionCode.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionResponse.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/GlobalExceptionHandler.java
Labels: 🛠️INIT🛠️

#28 [feat] Board 관련 엔티티메서드 추가
  backend/src/main/java/org/prgrms/devconnect/board/entity/Board.java
  backend/src/main/java/org/prgrms/devconnect/board/entity/BoardTechStackMapping.java
Labels: ✨FEAT✨

#32 refactor: 예외처리 로직 수정
  backend/src/main/java/org/prgrms/devconnect/common/exception/DevConnectException.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/board/BoardException.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/member/MemberException.java
Labels: :hammer:refactor:hammer:

#39 [feat] QueryDsl 세팅
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/org/prgrms/devconnect/domain/config/QueryDslConfig.java
Labels: ✨FEAT✨

#38 [feat] 회원 가입 및 로그인 기능 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/MemberController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/dto/request/MemberCreateRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/dto/request/MemberLoginRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/dto/request/MemberTechStackRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/service/member/MemberCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/member/MemberQueryService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/member/MemberService.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionCode.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/techstack/TechStackException.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/member/entity/Member.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/member/entity/MemberTechStackMapping.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/member/repository/MemberRepository.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/techstack/entity/TechStack.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/techstack/repository/TechStackRepository.java
Labels: ✨FEAT✨

#40 [feat] 모집글 작성 기능 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/BoardController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/dto/request/BoardCreateRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/board/dto/request/BoardTechStackRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/entity/Board.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/entity/BoardTechStackMapping.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/board/repository/BoardRepository.java
  backend/src/test/java/org/prgrms/devconnect/board/MemberFixture.java
  backend/src/test/java/org/prgrms/devconnect/board/TechStackFixture.java
  backend/src/test/java/org/prgrms/devconnect/board/service/BoardServiceTest.java
Labels: ✨FEAT✨

#41 [feat] 회원 정보 조회 및 수정 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/MemberController.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/dto/request/MemberCreateRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/dto/request/MemberTechStackRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/dto/request/MemberUpdateRequestDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/member/dto/response/MemberResponseDto.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/techstack/dto/response/TechStackResponseDto.java
  backend/src/main/java/org/prgrms/devconnect/api/service/member/MemberCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/member/MemberQueryService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/techstack/TechStackQueryService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/member/entity/Member.java
Labels: ✨FEAT✨

#44 [feat] : Swagger 적용
  backend/build.gradle
  backend/src/main/resources/application.yaml
Labels: ✨FEAT✨

#47 [feat] 기술 스택 기본 기능 구현
  backend/src/main/java/org/prgrms/devconnect/api/service/techstack/TechStackQueryService.java
  backend/src/test/java/org/prgrms/devconnect/api/service/board/BoardServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/api/service/techstack/TechStackQueryServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/domain/define/fixture/MemberFixture.java
  backend/src/test/java/org/prgrms/devconnect/domain/define/fixture/TechStackFixture.java
Labels: ✨FEAT✨

#46 [feat] 채팅 생성 및 채팅방 나가기 기능 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/ChattingControllor.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/request/ChatRoomRequest.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/response/ChatRoomResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/service/board/BoardService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/chatting/ChattingCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/member/MemberCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/member/MemberQueryService.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/ExceptionCode.java
  backend/src/main/java/org/prgrms/devconnect/common/exception/chatting/ChattingException.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/entity/ChatParticipation.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/entity/ChattingRoom.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/repository/ChatParticipationRepository.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/repository/ChattingRoomRepository.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/member/entity/Member.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/member/repository/MemberRepository.java
  backend/src/test/java/org/prgrms/devconnect/chatting/ChattingServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/chatting/entity/ChattingRoomTest.java
Labels: ✨FEAT✨

#50 [FEAT] 회원가입시 알림 메시지 기능 구현
  backend/src/main/java/org/prgrms/devconnect/DevconnectApplication.java
  backend/src/main/java/org/prgrms/devconnect/api/service/alarm/AlarmService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/member/MemberCommandService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/aop/AlarmCreater.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/aop/RegisterPublisher.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/entity/Alarm.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/event/EventHandler.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/event/RegisteredWelcomeEvent.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/alarm/repository/AlarmRepository.java
  backend/src/test/java/org/prgrms/devconnect/alarm/service/AlarmServiceTest.java
Labels: ✨FEAT✨

#51 [feat]채팅방 목록 조회 기능 구현
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/ChattingControllor.java
  backend/src/main/java/org/prgrms/devconnect/api/controller/chatting/dto/response/ChatRoomListResponse.java
  backend/src/main/java/org/prgrms/devconnect/api/service/chatting/ChattingCommandService.java
  backend/src/main/java/org/prgrms/devconnect/api/service/chatting/ChattingQueryService.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/repository/ChatParticipationRepository.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/repository/custom/ChatPartRepositoryCustom.java
  backend/src/main/java/org/prgrms/devconnect/domain/define/chatting/repository/custom/ChatPartRepositoryCustomImpl.java
  backend/src/test/java/org/prgrms/devconnect/domain/define/chatting/ChattingServiceTest.java
  backend/src/test/java/org/prgrms/devconnect/domain/define/chatting/entity/ChattingRoomTest.java
Labels: ✨FEAT✨
